server.port: 8080

security.user.password: 1234

# spring.datasource.url: jdbc:mysql://127.0.0.1:3306/italent
# spring.datasource.username: root
# spring.datasource.password: 123Root123
# spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.datasource.url: jdbc:mysql://127.8.154.2:3306/italent
spring.datasource.username: adminkgnI5Nk
spring.datasource.password: HiGAW1BJfshb
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto: create-drop
